---
- name: Verificando um valor estranho
  hosts: all
  tasks:
  - name: Verificando no Centos/OpenSUSE
    shell: 'echo {{ansible_distribution}} $USER'
    register: output
  - name: Inspecionando a variavel
    debug:
      msg: ' A saida foi {{output.stdout}}'  
    #  - name: Verifivando no Debian
    # shell: 'echo {{ansible_distribution}}'
